WORKDIR: ./
protocol: ENCODE4
MANIFEST: example/Example_manifest.csv

# Annotation files
GFF: annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz
PARTITION: annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.bed.gz
FEATURE_ANNOTATIONS: annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz
ACCESSION_RANKINGS: annotations/accession_type_ranking.txt
GENOME: annotations/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta
STAR_DIR: annotations/genome_ref
CHROM_SIZES: annotations/genome_ref/chrNameLength.txt
REPEAT_TABLE: annotations/repeatmasker.grch38.tsv.gz
REPEAT_BED: annotations/repeatmasker.grch38.sort.unique.bed.gz
BLACKLIST: annotations/encode3_eclip_blacklist.bed
GENE_SETS: annotations/c5.go.v7.5.1.symbols.gmt
GENE_SET_REFERENCE: annotations/encode3_go_terms.reference.tsv.gz
GENE_SET_DISTANCE: annotations/encode3_go_terms.jaccard_index.rds

# Skipper parameters
UMI_SIZE: 10
INFORMATIVE_READ: 1
UNINFORMATIVE_READ: 2
OVERDISPERSION_MODE: input   # input or clip

# Tools and scripts
TOOL_DIR: tools
RBPNET_PATH: /tscc/nfs/home/hsher/projects/RBPNet/
TMPDIR: tmp

# Population genetics / VCF-related
HEADER: /tscc/nfs/home/hsher/bin/Roulette/header.hr
RENAME: /tscc/nfs/home/hsher/projects/oligoCLIP/utils/rename_chr.txt
ROULETTE_DIR: /tscc/nfs/home/hsher/ps-yeolab5/roulette/
GNOMAD_DIR: /tscc/nfs/home/hsher/ps-yeolab5/gnomAD/v4/
CLINVAR_VCF: /tscc/projects/ps-yeolab5/hsher/clinvar/clinvar.vcf.gz
VEP_CACHEDIR: /tscc/nfs/home/hsher/scratch/vep_cache/
VEP_CACHE_VERSION: 113
SINGLETON_REFERENCE: popgen_reference/singleton_adjust.coef.csv
OE_RATIO_REFERENCE: popgen_reference/vep.csv
GNOMAD_CONSTRAINT: popgen_reference/gnomad.v4.0.constraint_metrics.tsv