WORKDIR: /tscc/nfs/home/hsher/scratch/ENCODE3_K562_failed
protocol: ENCODE3
MANIFEST: /tscc/nfs/home/hsher/projects/skipper/encode_configs/K562_failed.csv
GFF : /tscc/projects/ps-yeolab4/software/skipper/bb63a25/bin/skipper/annotations/gencode.v40.annotation.k562_totalrna.gt1.gff3.gz
PARTITION : /tscc/projects/ps-yeolab4/software/skipper/bb63a25/bin/skipper/annotations/gencode.v40.annotation.k562_totalrna.gt1.tiled_partition.bed.gz
FEATURE_ANNOTATIONS : /tscc/projects/ps-yeolab4/software/skipper/bb63a25/bin/skipper/annotations/gencode.v40.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz
ACCESSION_RANKINGS : /tscc/projects/ps-yeolab4/software/skipper/bb63a25/bin/skipper/annotations/accession_type_ranking.txt
UMI_SIZE : 10
INFORMATIVE_READ : 2
OVERDISPERSION_MODE : clip
TOOL_DIR : /tscc/projects/ps-yeolab3/hsher/skipper/tools
STAR_DIR : /tscc/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/
GENOME : /tscc/projects/ps-yeolab4/genomes/GRCh38/chromosomes/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta
CHROM_SIZES : /tscc/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/chrNameLength.txt
REPEAT_TABLE : /tscc/projects/ps-yeolab4/software/skipper/bb63a25/bin/skipper/annotations/repeatmasker.grch38.tsv.gz
BLACKLIST : /tscc/projects/ps-yeolab4/software/skipper/bb63a25/bin/skipper/annotations/encode3_eclip_blacklist.bed
GENE_SETS : /tscc/projects/ps-yeolab4/software/skipper/bb63a25/bin/skipper/annotations/c5.go.v7.5.1.symbols.gmt
GENE_SET_REFERENCE : /tscc/projects/ps-yeolab4/software/skipper/bb63a25/bin/skipper/annotations/encode3_go_terms.reference.tsv.gz
GENE_SET_DISTANCE : /tscc/projects/ps-yeolab4/software/skipper/bb63a25/bin/skipper/annotations/encode3_go_terms.jaccard_index.rds
UNINFORMATIVE_READ : 1
REPEAT_BED : /tscc/projects/ps-yeolab3/eboyle/encode/pipeline/05_20220720/repeatmasker.grch38.sort.unique.bed.gz
RBPNET_PATH: /tscc/nfs/home/hsher/projects/RBPNet/
TMPDIR: /tscc/nfs/home/hsher/scratch/
# related to vcfs
HEADER: /tscc/nfs/home/hsher/bin/Roulette/header.hr
RENAME: /tscc/nfs/home/hsher/projects/oligoCLIP/utils/rename_chr.txt
ROULETTE_DIR: /tscc/nfs/home/hsher/ps-yeolab5/roulette/
GNOMAD_DIR: /tscc/nfs/home/hsher/ps-yeolab5/gnomAD/v4/
CLINVAR_VCF: /tscc/projects/ps-yeolab5/hsher/clinvar/clinvar.vcf.gz
VEP_CACHEDIR: /tscc/nfs/home/hsher/scratch/vep_cache/
VEP_CACHE_VERSION: 113
# these are to scale the popgen metrics to the average intergenic variant
SINGLETON_REFERENCE: /tscc/nfs/home/hsher/projects/skipper/popgen_reference/singleton_adjust.coef.csv
OE_RATIO_REFERENCE: /tscc/nfs/home/hsher/projects/skipper/popgen_reference/vep.csv
GNOMAD_CONSTRAINT: /tscc/nfs/home/hsher/projects/skipper/popgen_reference/gnomad.v4.0.constraint_metrics.tsv

