verbose: true
notemp: false
latency: 60
printshellcmds: true
cores: 1
skip-script-cleanup: true
nolock: true
keep-going: true
--singularity-prefix: /tscc/projects/ps-yeolab4/software/skipper/1.99.0/bin/.singularity
use-singularity: true
singularity-args: "--bind /tscc"
retries: 3
resources: mem_mb=16000
cluster: "sbatch --partition condo --qos=condo --account csd792 --nodes=1 --tasks-per-node={threads} --error={params.error_file} --output={params.out_file} --time={params.run_time} --mem={params.memory}M"
jobs: 16
